// MMPI Ham Veri Modülü
// Bu dosya MMPI testinin tüm statik verilerini (sorular, puanlama, normlar) içerir

// 566 MMPI Sorusu
export const mmpiQuestions = [
{ "id": "1", "metin": "Teknik yazılardan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "2", "metin": "İştahım iyidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "3", "metin": "Çok defa sabahları dinç ve dinlenmiş olarak uyanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "4", "metin": "Kütüphaneci olarak çalışmayı seveceğimi sanıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "5", "metin": "Gürültüden kolayca uyanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "6", "metin": "Cinayet haberlerini okumaktan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "7", "metin": "Çoğu zaman el ve ayaklarımın sıcaklığı iyidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "8", "metin": "Günlük hayatım beni ilgilendirecek şeylerle doludur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "9", "metin": "Bugün de hemen hemen eskisi kadar iyi çalışabiliyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "10", "metin": "Çoğu zaman boğazım tıkanır gibi olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "11", "metin": "İnsan rüyalarını anlamaya çalışmalı ve kendini onlara göre ayarlamalıdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "12", "metin": "Polis romanlarından ya da esrarengiz yazılardan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "13", "metin": "Büyük bir sinir gerginliği içinde çalışırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "14", "metin": "Ayda bir iki defa ishal olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "15", "metin": "Arasıra söylenemeyecek kadar ayıp şeyler düşünürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "16", "metin": "Hayatta kötülükler hep beni bulur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "17", "metin": "Babam iyi bir adamdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "18", "metin": "Pek seyrek kabız olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "19", "metin": "Yeni bir işe girince kimin gözüne girmem gerektiğini öğrenmek isterim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "20", "metin": "Cinsel yaşamımdan memnunum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "21", "metin": "Zaman zaman evi bırakıp gitmek istemişimdir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "22", "metin": "Arasıra kontrol edemediğim gülme ve ağlama nöbetlerine tutulurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "23", "metin": "Tekrarlanan mide bulantısı ve kusmalar bana sıkıntı verir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "24", "metin": "Kimse beni anlamıyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "25", "metin": "Şarkıcı olmayı isterim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "26", "metin": "Başım derde girince susmayı tercih ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "27", "metin": "Bazen kötü ruhların beni etkileri altına aldığını hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "28", "metin": "Kötülüğe kötülükle karşılık vermek prensibimdir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "29", "metin": "Çoğu kez midem ekşir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "30", "metin": "Bazen canım küfretmek ister.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "31", "metin": "Sık sık geceleri kabus geçiririm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "32", "metin": "Zihnimi bir iş üzerinde toplamada güçlük çekerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "33", "metin": "Başımdan çok garip ve tuhaf şeyler geçti.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "34", "metin": "Çoğu zaman öksürüğüm vardır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "35", "metin": "Başkaları engel olmasaydı daha çok başarılı olurdum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "36", "metin": "Sağlığım beni pek kaygılandırmaz.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "37", "metin": "Cinsel yaşamım yüzünden başım hiç derde girmedi.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "38", "metin": "Gençliğimde bir devre ufak tefek şeyler çaldım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "39", "metin": "Bazen içimde bir şeyler kırmak isteği geçer.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "40", "metin": "Başka bir şey yapmaktansa çoğu zaman oturup hayal kurmayı severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "41", "metin": "Kendimi toparlayamadığım için günler, haftalar hatta aylarca hiç bir şeye el sürmediğim olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "42", "metin": "Ailem seçtiğim (veya seçmek istediğim) mesleği beğenmiyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "43", "metin": "Kuşkulu ve rahatsız uyurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "44", "metin": "Çoğu zaman başımın her tarafı ağrır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "45", "metin": "Her zaman doğruyu söylemem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "46", "metin": "Şimdi her zamankinden daha iyi düşünüp tartabiliyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "47", "metin": "Ortada hiç bir neden yokken haftada bir ya da daha sık birdenbire her yanımı ateş basar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "48", "metin": "Başkaları ile bir arada iken kulağıma çok garip şeyler gelmesinden rahatsız olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "49", "metin": "Kanunların hemen hepsi kaldırılırsa daha iyi olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "50", "metin": "Bazen ruhum vücudumdan ayrılır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "51", "metin": "Sağlığım bir çok arkadaşımınki kadar iyidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "52", "metin": "Uzun zamandan beri görmediğim okul arkadaşlarım ya da tanıdıklarım önce benimle konuşmazlarsa onları görmemezlikten gelmeyi tercih ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "53", "metin": "Hocaların dua okuyup üflemesi hastalığı iyileştirir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "54", "metin": "Tanıdıklarımın çoğu beni sever.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "55", "metin": "Kalp ve göğüs ağrılarından hemen hemen hiç şikayetim yoktur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "56", "metin": "Çocukken okuldan kaçtığım için bir iki defa cezalandırıldım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "57", "metin": "İnsanlarla çabucak kaynaşırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "58", "metin": "Kur'an'ın buyurdukları bir bir çıkmaktadır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "59", "metin": "Çok defa benden az bilenlerden emir alarak çalışmak zorunda kaldım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "60", "metin": "Her gün gazetelerin baş yazılarını okumam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "61", "metin": "Gerektiği gibi bir hayat yaşayamadım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "62", "metin": "Vücudumun bazı yerlerinde çok defa yanma, gıdıklanma, karıncalanma veya uyuşukluk hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "63", "metin": "Büyük abdest yapmada ya da tutmada hiç bir güçlük çekmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "64", "metin": "Bazen başkalarının sabrını tüketecek kadar bir şeye saplanıp kalırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "65", "metin": "Babamı severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "66", "metin": "Etrafımda başkalarının görmedikleri eşya ve hayvanlar ya da insanlar görürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "67", "metin": "Başkalarının mutlu göründüğü kadar mutlu olmayı isterdim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "68", "metin": "Ensemde nadiren ağrı hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "69", "metin": "Kendi cinsimden olanları oldukça çekici bulurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "70", "metin": "Körebe oyunundan hoşlanırdım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "71", "metin": "Birçok kimseler başkalarının ilgi ve yardımlarını sağlamak için talihsizliklerini abartırlar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "72", "metin": "Hemen hemen her gün mide ağrılarından rahatsız olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "73", "metin": "Ben önemli bir kimseyim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "74", "metin": "Çoğu zaman kız olmayı isterdim. (Şayet kız iseniz) Kız olduğuma hiç üzülmedim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "75", "metin": "Arasıra öfkelenirim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "76", "metin": "Çoğu zaman kendimi hüzünlü hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "77", "metin": "Aşk romanları okumaktan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "78", "metin": "Şiiri severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "79", "metin": "Kolay incinmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "80", "metin": "Bazen hayvanlara rahat vermem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "81", "metin": "Orman bekçiliği gibi işlerden hoşlanacağımı sanıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "82", "metin": "Tartışmalarda çabucak yenilirim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "83", "metin": "Çok çalışabilen ya da çalışmak isteyen kişinin başarılı olma şansı yüksektir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "84", "metin": "Bügünlerde artık hiç ilerleme umudum kalmamış gibi hissediyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "85", "metin": "Kullanamayacak bile olsam bazen başkalarının ayakkabı, eldiven vb. gibi özel eşyaları okadar hoşuma gider ki dokunmak ve aşırmak isterim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "86", "metin": "Kendime hiç güvenim yoktur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "87", "metin": "Çiçek satıcısı olmayı isterdim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "88", "metin": "Genel olarak hayatın yaşanmaya değer olduğu kanısındayım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "89", "metin": "İnsanlara gerçeği kabul ettirmek güçtür.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "90", "metin": "Bugün yapmam gereken işleri ara sıra yarına bıraktığım olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "91", "metin": "Benimle alay edilmesine aldırmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "92", "metin": "Hemşire olmayı isterdim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "93", "metin": "Yükselmek için bir çok kimse yalan söylemekten çekinmez.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "94", "metin": "Sonradan pişman olacağım pek çok şeyi yaptığım olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "95", "metin": "Namazımı hemen hemen muntazaman kılarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "96", "metin": "Ailemle pek az kavga ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "97", "metin": "Bazen zararlı ya da çok kötü işler yapmak için içimde çok güçlü bir istek duyarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "98", "metin": "Kıyamet gününe inanıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "99", "metin": "Gürültülü eğlencelere katılmaktan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "100", "metin": "Bildiğim bir konuda bir kimse saçma sapan ya da cahilce konuşursa onu hemen düzeltirim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "101", "metin": "Bence cinsel yönden kadınlar da erkekler kadar serbest olmalıdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "102", "metin": "En büyük mücadelelerimi kendimle yaparım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "103", "metin": "Vücudumda pek az seyirme ve kasılma olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "104", "metin": "Başıma ne gelirse gelsin aldırış etmiyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "105", "metin": "Keyfim yerinde olmadığı zaman tersliğim üzerimdedir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "106", "metin": "Çoğu zaman büyük bir hata ya da kötülük yaptığım duygusuna kapılırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "107", "metin": "Çoğu zaman mutluyumdur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "108", "metin": "Çoğu zaman bana, kafam şişmiş ya da burnum tıkanmış gibi gelir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "109", "metin": "Bazı kimseler o kadar amirane davranırlar ki haklı bile olsalar içimden dediklerinin aksini yapmak gelir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "110", "metin": "Bana kötülük etmek isteyen biri var.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "111", "metin": "Sırf heyecanlanmak için tehlikeli bir işe girişmedim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "112", "metin": "Doğru bildiğim şeyler için çoğu zaman direnmek zorunda kalırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "113", "metin": "Kanunların uygulanması gerektiğine inanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "114", "metin": "Çoğu zaman başım sıkı bir çember içindeymiş gibi hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "115", "metin": "Ahirete inanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "116", "metin": "Bahse girdiğim yarış ya da oyunlardan daha çok zevk alırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "117", "metin": "Bir çok kimseler daha çok yakalanmaktan korktukları için dürüsttürler.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "118", "metin": "Dersten kaçtığım için ara sıra müdüre gönderildiğim oldu.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "119", "metin": "Konuşma tarzım her zamanki gibidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "120", "metin": "Evde sofra adabına dışarıdaki kadar dikkat etmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "121", "metin": "Aleyhimde bazı tertipler kurulduğuna inanıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "122", "metin": "Tanıdığım insanların çoğu kadar becerikli ve zeki olduğumu sanıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "123", "metin": "Beni takip edenler olduğuna inanıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "124", "metin": "Birçokları kaybetmektense çıkarlarını korumak için pek doğru olmayan yollara başvururlar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "125", "metin": "Midemden oldukça rahatsızım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "126", "metin": "Tiyatrodan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "127", "metin": "Dertlerimin çoğundan kimin sorumlu olduğunu biliyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "128", "metin": "Kan görünce korkmam ya da fenalaşmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "129", "metin": "Bazen ters ve suratsız olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "130", "metin": "Hiç bir zaman kan kusmadım ya da kan tükürmedim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "131", "metin": "Hastalığa yakalanacağım diye kaygılanmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "132", "metin": "Çiçek koleksiyonu yapmayı ve evde çiçek yetiştirmeyi severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "133", "metin": "Hiçbir zaman normal olmayan cinsel ilişkilere girişmedim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "134", "metin": "Bazen kafamdaki düşünceler o kadar hızlıdır ki söylemeyi yetiştiremem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "135", "metin": "Farkedilmeyeceğimden emin olsam sinemaya biletsiz girerdim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "136", "metin": "Bana iyilik yapan kimselerin genel olarak gizli bir amacı olabileceğini düşünürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "137", "metin": "Aile hayatımın tanıdığım kimselerin çoğunki kadar iyi olduğuna inanıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "138", "metin": "Eleştiri beni çok kırar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "139", "metin": "Bazen sanki kendimi ya da başkasını incitmek zorundaymışım gibi hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "140", "metin": "Yemek pişirmeyi severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "141", "metin": "Davranışlarımı çoğu zaman etrafımdakilere göre ayarlarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "142", "metin": "Bazen hiçbir işe yaramadığımı düşünürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "143", "metin": "Çocukken başlarına ne gelirse gelsin aralarındaki birliği koruyan bir gruptaydım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "144", "metin": "Asker olmak isterim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "145", "metin": "Bazen biriyle yumruk yumruğa kavgaya girişmek istediğim olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "146", "metin": "Seyahat edip gezip tozmadıkça mutlu olamam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "147", "metin": "Çabuk karar vermediğim için çok fırsat kaçırdım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "148", "metin": "Önemli bir iş üzerinde çalışırken başkalarının işimi yarıda kesmeleri sabrımı taşırır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "149", "metin": "Hatıra defteri tutardım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "150", "metin": "Oyunda kaybetmektense kazanmayı isterim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "151", "metin": "Biri beni zehirlemeye çalışıyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "152", "metin": "Çoğu geceler zihnimi hiçbir şey kurcalamadan uykuya dalarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "153", "metin": "Son bir kaç yıl içinde sağlığım çoğu zaman iyi idi.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "154", "metin": "Hiç sinir nöbeti ya da havale geçirmedim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "155", "metin": "Ne şişmanlıyorum ne de zayıflıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "156", "metin": "Bir şeyler yapıp sonra ne yaptığımı hatırlayamadığım zamanlar oldu.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "157", "metin": "Çoğu kez sebepsiz yere cezalandırıldım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "158", "metin": "Çabuk ağlarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "159", "metin": "Okuduğumu eskisi kadar iyi anlayamıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "160", "metin": "Hayatımda hiçbir zaman kendimi şimdiki kadar iyi hissetmedim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "161", "metin": "Bazen başımda bir sızı hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "162", "metin": "Birisinin bana kurnazca oyun etmesine çok içerlerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "163", "metin": "Çabucak yorulmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "164", "metin": "Üzerinde çalıştığım konularda okumayı ve incelemelerde bulunmayı severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "165", "metin": "Önemli kimseleri tanımayı severim, çünkü böylece kendimi de önemli bir kimse gibi görürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "166", "metin": "Yüksek bir yerden aşağıya bakmaya korkarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "167", "metin": "Ailemden herhangi birinin mahkemelik olması beni rahatsız etmez.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "168", "metin": "Zihnimde bir gariplik var.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "169", "metin": "Parayı ellemekten korkmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "170", "metin": "Başkalarının hakkımda ne düşündükleri beni rahatsız etmez.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "171", "metin": "Bir eğlencede başkaları yapsalar bile, ben taşkınlık yapmaktan rahatsız olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "172", "metin": "Çoğu kez utangaçlığımı örtbas etmek ihtiyacını duyarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "173", "metin": "Okulu severdim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "174", "metin": "Hiç bayılma nöbeti geçirmedim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "175", "metin": "Pek az başım döner ya da hiç dönmez.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "176", "metin": "Yılandan büyük bir korkum yoktur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "177", "metin": "Annem iyi bir kadındır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "178", "metin": "Hafızam genellikle iyidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "179", "metin": "Cinsel konularda sıkıntım vardır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "180", "metin": "Yeni tanıştığım kimselerle konuşma konusu bulmada güçlük çekerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "181", "metin": "Canım sıkılınca heyecan yaratmayı severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "182", "metin": "Aklımı oynatmaktan korkuyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "183", "metin": "Dilencilere para vermeyi doğru bulmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "184", "metin": "Sık sık nereden geldiğini bilmediğim sesler duyarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "185", "metin": "Herkes kadar iyi işitirim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "186", "metin": "Bir şeyler yapmaya girişince ellerimin çok defa titrediğini fark ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "187", "metin": "Ellerimde beceriksizlik ya da sakarlık yok.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "188", "metin": "Gözlerim yorulmadan uzun süre okuyabilirim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "189", "metin": "Çoğu zaman bütün vücudumda bir halsizlik duyarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "190", "metin": "Başım pek az ağrır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "191", "metin": "Bazen utanınca çok terlerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "192", "metin": "Yürürken dengemi hemen hemen hiç kaybetmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "193", "metin": "Saman nezlesi ya da astım nöbetlerim yoktur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "194", "metin": "Hareketlerimi ve konuşmamı kontrol edemediğim fakat etrafımda olup bitenden haberdar olduğum nöbetler geçirdiğim oldu.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "195", "metin": "Tanıdığım herkesi sevmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "196", "metin": "Hiç görmediğim yerlere gitmekten hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "197", "metin": "Biri beni soymaya (her şeyimi almaya) çalışıyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "198", "metin": "Çok az hayal kurarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "199", "metin": "Çocuklara cinsiyetle ilgili temel gerçekler öğretilmelidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "200", "metin": "Fikir ve düşüncelerimi çalmak isteyen biri var.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "201", "metin": "Keşke bu kadar utangaç olmasam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "202", "metin": "Kendimi cezayı hak etmiş suçlu bir insan olarak görüyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "203", "metin": "Gazeteci olmak isterdim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "204", "metin": "Gazeteci olsaydım daha çok tiyatro haberleri yazmaktan hoşlanırdım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "205", "metin": "Bazen çalmaktan ya da dükkanlardan eşya aşırmaktan kendimi alamam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "206", "metin": "Bir çok kimseden daha çok dindarımdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "207", "metin": "Çeşitli oyun ve eğlencelerden hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "208", "metin": "Flört etmeyi severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "209", "metin": "Günahlarımın affedilmeyeceğine inanıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "210", "metin": "Her şeyin tadı aynı geliyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "211", "metin": "Gündüzleri uyuyabilirim fakat geceleri uyuyamam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "212", "metin": "Evdekiler bana çocuk muamelesi yapıyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "213", "metin": "Yürürken kaldırımdaki yarıklara basmamaya dikkat ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "214", "metin": "Cildimde üzülmeye değer kabarıklık ya da sivilce yok.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "215", "metin": "Çok içki kullandım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "216", "metin": "Başka ailelere göre bizim evde sevgi ve arkadaşlık pek azdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "217", "metin": "Sık sık kendime bir şeyleri dert edinirim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "218", "metin": "Hayvanların eziyet çektiğini görmek beni üzmez.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "219", "metin": "İnşaat müteahhitliğinden hoşlanacağımı sanıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "220", "metin": "Annemi çok severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "221", "metin": "Bilimden hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "222", "metin": "Karşılığını veremeyeceğim durumlarda bile arkadaşlarımdan yardım istemekte güçlük çekmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "223", "metin": "Avlanmayı çok severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "224", "metin": "Annem babam hep beraber olduğum kimselerden çok defa hoşlanmıyorlar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "225", "metin": "Bazen biraz dedikodu yaptığım olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "226", "metin": "Ailemdeki bazı kişilerde canımı çok sıkan alışkanlıklar var.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "227", "metin": "Uykuda gezdiğimi söylerler", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "228", "metin": "Bazen alışılmamış bir kolaylıkla karar verebileceğimi hissediyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "229", "metin": "Çeşitli kulüp ve derneklere üye olmayı isterim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "230", "metin": "Kalbimin hızlı çarptığını hemen hemen hiç hissetmem ve çok seyrek nefesim tıkanır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "231", "metin": "Cinsiyet hakkında konuşmayı severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "232", "metin": "Bazen üzerime çok fazla iş alırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "233", "metin": "Pek çok insan karşı çıksa da kendi fikrimi sonuna kadar savunurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "234", "metin": "Çabuk kızar ve çabuk unuturum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "235", "metin": "Aile kurallarından oldukça bağımsız ve özgürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "236", "metin": "Sıklıkla kara kara düşünürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "237", "metin": "Akrabalarımın hemen hepsi bana karşı anlayış gösterir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "238", "metin": "Zaman zaman yerimde duramayacak kadar huzursuzluk duyduğum devreler olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "239", "metin": "Aşkta hayal kırıklığına uğradım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "240", "metin": "Görünüşüme hiç aldırmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "241", "metin": "Kendi içimde tutup başkalarına söylenemeyen şeyler hakkında sık sık rüya görürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "242", "metin": "Bir çoklarından daha sinirli sayılmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "243", "metin": "Hemen hemen hiçbir ağrı ve sızım yok.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "244", "metin": "Davranışlarım başkalarınca yanlış anlaşılmaya elverişlidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "245", "metin": "Ailem beni olduğumdan daha hatalı bulur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "246", "metin": "Boynumda sık sık kırmızı lekeler olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "247", "metin": "Kimseden sevgi görmüyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "248", "metin": "Bazen ortada hiçbir neden yokken hatta işler kötüye gittiği zaman bile kendimi fazlasıyla mutlu hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "249", "metin": "Öbür dünyada şeytan ve cehennem olduğuna inanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "250", "metin": "Hayatta önüne her geleni kapmağa çalışan insanları suçlamam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "251", "metin": "Kendimi kaybedip yaptığım işi aksattığım ve etrafımda olup bitenlerin farkında olmadığım zamanlar oldu.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "252", "metin": "Hiç kimse başkasının derdine aldırış etmiyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "253", "metin": "Hatalı davranışlarını görsem bile insanlara arkadaşça davranabilirim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "254", "metin": "Birbiriyle şakalaşan kimseler arasında olmayı severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "255", "metin": "Seçimlerde bazen oyumu pek az tanıdığım kimselere veririm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "256", "metin": "Gazetelerin ilgi çeken tek yeri resimli mizah sayfasıdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "257", "metin": "Yaptığım işlerde genel olarak başarı elde edeceğime inanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "258", "metin": "Allah'ın varlığına inanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "259", "metin": "İşe başlamada güçlük çekerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "260", "metin": "Okulda iken ağır öğrenenlerden biri idim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "261", "metin": "Ressam olsaydım çiçek resimleri yapardım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "262", "metin": "Daha güzel olmamam beni rahatsız etmez.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "263", "metin": "Soğuk günlerde bile kolayca terlerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "264", "metin": "Kendime tam anlamıyla güvenim vardır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "265", "metin": "Hiç kimseye güvenmemek en doğrusudur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "266", "metin": "Haftada bir ya da daha sık, çok heyecanlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "267", "metin": "Topluluk içinde olduğumda üzerinde konuşacak uygun konular bulmakda güçlük çekerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "268", "metin": "Karamsar olduğum zaman heyecanlı bir olay hemen beni bu durumdan çıkarır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "269", "metin": "Bazen zevk için başkalarını kendimden korkuturum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "270", "metin": "Evden çıkarken kapının kilitli ve pencerenin kapalı olup olmadığı aklıma takılmaz.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "271", "metin": "Başkalarının saflığını kendi çıkarlarına kullanan kimseleri ayıplamam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "272", "metin": "Bazen kendimi enerji dolu hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "273", "metin": "Derimin bazı yerlerinde uyuşukluk hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "274", "metin": "Görme gücüm eskisi kadar kuvvetlidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "275", "metin": "Birisi zihnimi kontrol ediyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "276", "metin": "Çocukları severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "277", "metin": "Bazen bir madrabazın(Hilecinin) kurnazlığı beni o kadar eğlendirir ki yakayı ele vermemesini dilerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "278", "metin": "Çok defa tanımadığım kimselerin bana eleştirici bir gözle baktıklarını hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "279", "metin": "Her gün gereğinden fazla su içerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "280", "metin": "Birçok kimseler kendilerine yararı dokunacağı için arkadaş edinirler.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "281", "metin": "Kulaklarım çok az çınlar ya da uğuldar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "282", "metin": "Genellikle sevdiğim aile üyelerine karşı bazen nefret duyarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "283", "metin": "Gazete muhabiri olsaydım en çok spor haberleri yazmayı isterdim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "284", "metin": "Hakkımda çok konuşulduğundan eminim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "285", "metin": "Arasıra açık saçık bir fıkraya güldüğüm olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "286", "metin": "En çok yalnız olduğum zaman mutlu olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "287", "metin": "Arkadaşlarıma kıyasla beni korkutan şeyler çok azdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "288", "metin": "Tekrarlanan mide bulantısı ve kusmalar bana sıkıntı verir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "289", "metin": "Bir suçlu avukatın becerikliliği sayesinde cezadan kurtulunca kanunlara karşı daima nefret duyarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "290", "metin": "Çok gergin bir hava içinde çalışıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "291", "metin": "Hayatımda bir ya da birkaç kere birisinin beni hipnotize ederek bana birşeyler yaptığını hissettim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "292", "metin": "Başkaları benimle konuşuncaya kadar ben onlarla konuşmağa başlamam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "293", "metin": "Birisi zihnimi etkilemeye çalışıyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "294", "metin": "Kanunla hiç başım derde girmedi.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "295", "metin": "Masal okumayı severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "296", "metin": "Hiçbir neden yokken kendimi son derece neşeli hissettiğim zamanlar olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "297", "metin": "Cinsiyetle ilgili düşünceler beni rahatsız eder.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "298", "metin": "Birkaç kişinin birlikte başları derde girince en iyisi yakalarını kurtarmak için aynı hikayeyi uydurmak ve bundan caymamaktır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "299", "metin": "Duygularımın birçok kimselerden yoğun olduğunu düşünürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "300", "metin": "Hayatımda hiçbir zaman bebekle oynamaktan hoşlanmadım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "301", "metin": "Çoğu zaman hayat benim için bir yüktür.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "302", "metin": "Cinsel davranışlarımdan dolayı hiçbir zaman başım derde girmedi.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "303", "metin": "Bazı konularda o kadar alınganım ki onlar hakkında konuşmam bile.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "304", "metin": "Okulda sınıf karşısında konuşmak bana çok güç gelirdi.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "305", "metin": "Başkalarıyla beraber olduğum zaman bile kendimi yalnız hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "306", "metin": "Bana karşı mümkün olan anlayış gösteriliyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "307", "metin": "İyi beceremediğim oyunları oynamaya yanaşmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "308", "metin": "Zaman zaman evi bırakıp gitmeyi çok istemişimdir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "309", "metin": "Birçokları kadar çabuk arkadaş edinebildiğimi sanıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "310", "metin": "Cinsel hayatım doyurucudur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "311", "metin": "Gençlik yıllarımda bir devre ufak tefek şeyler çaldım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "312", "metin": "İnsanların arasında olmaktan hiç hoşlanmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "313", "metin": "Değerli eşyasını tedbirsizce ortada bırakıp çalınmasına neden olan kimse bunu çalan kadar hatalıdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "314", "metin": "Arasıra söylenemeyecek kadar kötü şeyler düşünürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "315", "metin": "Hayatın hep kötü tarafları bana nasip olmuştur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "316", "metin": "Hemen hemen herkesin başını derde sokmamak için yalan söyleyebileceğine inanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "317", "metin": "Birçok kimselerden daha hassasım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "318", "metin": "Günlük hayatım beni ilgilendiren şeylerle dolu.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "319", "metin": "İnsanların çoğu başkalarına yardım etmek için zahmete girmekten hoşlanmazlar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "320", "metin": "Rüyalarımın çoğu cinsel konularla ilgilidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "321", "metin": "Kolaylıkla mahcup olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "322", "metin": "Para ve işi kendime dert ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "323", "metin": "Başımdan çok tuhaf ve acayip olaylar geçmiştir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "324", "metin": "Hiç kimseye aşık olmadım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "325", "metin": "Ailemin yaptığı bazı şeyler beni korkutmuştur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "326", "metin": "Bazen kontrol edemediğim gülme ve ağlama nöbetlerine tutulurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "327", "metin": "Annem ya da babam çok defa beni makul bulmadığım emirlere bile itaat ettirdiler.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "328", "metin": "Zihnimi bir konu ya da iş üzerinde toplamakta güçlük çekerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "329", "metin": "Hemen hemen hiç rüya görmedim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "330", "metin": "Hiç felç geçirmedim ya da kaslarımda olağanüstü bir halsizlik duymadım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "331", "metin": "Eğer insanlar sırf düşmanlık olsun diye beni engellemeselerdi daha başarılı olurdum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "332", "metin": "Bazen nezle olmadığım halde sesim çıkmaz ya da değişir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "333", "metin": "Beni hiç kimse anlamıyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "334", "metin": "Bazen tuhaf kokular duyarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "335", "metin": "Zihnimi bir konu üzerinde toplayamam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "336", "metin": "İnsanlara karşı sabrım çabuk tükenir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "337", "metin": "Çoğunlukla bir takım şeyler ve kimseler için meraklanıp huzursuzlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "338", "metin": "Hayatımın çoğu kimselerinkinden daha fazla tasa ve kaygı içinde geçtiğine eminim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "339", "metin": "Çoğu zaman ölmüş olmayı isterdim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "340", "metin": "Bazen o kadar heyecanlanırım ki uykuya dalmam güçleşir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "341", "metin": "Bazen beni rahatsız edecek kadar iyi işitirim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "342", "metin": "Bana söylenenleri hemen unuturum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "343", "metin": "Önemsiz ufak şeylerde bile karar verip işe girişmeden önce durur ve düşünürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "344", "metin": "Gördüğüm kimse ile karşılaşmamak için sıklıkla yolumu değiştiririm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "345", "metin": "Sıklıkla olup bitenler bana gerçek değilmiş gibi gelir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "346", "metin": "Reklamlardaki ampuller gibi önemsiz şeyleri sayma alışkanlığım vardır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "347", "metin": "Bana gerçekten kötülük yapmak isteyen hiçbir düşmanım yoktur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "348", "metin": "Bana umduğumdan fazla dostluk gösteren insanlara karşı tetikte bulunmağa çalışırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "349", "metin": "Acayip ve tuhaf düşüncelerim vardır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "350", "metin": "Yalnızken garip şeyler duyarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "351", "metin": "Küçük bir seyahat için bile evden ayrılırken telaşlanır ve kaygılanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "352", "metin": "Beni incitmeyeceğini bildiğim şeylerden ya da insanlardan bile korktuğum oldu.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "353", "metin": "Başkalarının daha önce toplanıp konuştuğu odaya girmekten çekinmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "354", "metin": "Bıçak gibi çok keskin ve sivri şeyler kullanmaktan korkarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "355", "metin": "Sevdiğim kimseleri bazen incitmekten hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "356", "metin": "Dikkatimi bir konu üzerinde toplamada birçok kişiden daha fazla güçlük çekerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "357", "metin": "Yeteneğimi küçümsediğim için birçok defalar başladığım işi yarıda bıraktım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "358", "metin": "Kötü ve çok defa korkunç kelimeler zihnimi kurcalar ve bunlardan kendimi kurtaramam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "359", "metin": "Bazen önemsiz düşünceler aklımdan geçer ve beni günlerce rahatsız eder.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "360", "metin": "Hemen hemen her gün beni korkutan bir şey olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "361", "metin": "Her şeyi kötüye yorma eğilimindeyim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "362", "metin": "Birçok kimselerden çok daha hassasım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "363", "metin": "Bazen sevdiğim kimselerin beni incitmesinden hoşlandığım oldu.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "364", "metin": "Hakkımda onur kırıcı ve kötü sözler söylüyorlar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "365", "metin": "Kapalı yerlerde huzursuzluk duyarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "366", "metin": "İnsanlar arasında bile olsam çok defa kendimi yalnız hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "367", "metin": "Yangından korkmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "368", "metin": "Sonradan pişman olacağım şeyler yapmak ya da söylemek korkusuyla bazen bir kimseden uzak durduğum oldu.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "369", "metin": "Kararsızlığım yüzünden yapılması gerekli bir çok işi yapamamışımdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "370", "metin": "Çalışırken acele etmek zorunda olmaktan nefret ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "371", "metin": "Aşırı derecede kendini dinleyen bir insan değilim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "372", "metin": "Elimdeki işi en iyi şekilde yapmayı isterim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "373", "metin": "Yalnızca bir tek doğru din olduğundan eminim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "374", "metin": "Ara sıra zihnim her zamankinden daha ağır işler.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "375", "metin": "Çok mutlu olduğum ve iyi çalıştığım zamanlarda neşesiz veya dertli bir insanla karşılaşmak keyfimi tamamen kaçırır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "376", "metin": "Polisler genellikle dürüsttür.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "377", "metin": "Toplantılarda kalabalığa karışmaktan çok yalnız başıma oturur ya da bir tek kişiyle ahbaplık ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "378", "metin": "Kadınları sigara içerken görmekten hoşlanmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "379", "metin": "Çok nadiren karamsarlığa kapılırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "380", "metin": "Ne yapsam zevk alamıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "381", "metin": "Kolay öfkelenen biri olduğumu söylerler.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "382", "metin": "Yapmak istediğim şeylere karar verirken, başkalarının ne düşüneceğini dikkate almam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "383", "metin": "İnsanlar çoğu zaman beni hayal kırıklığına uğratırlar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "384", "metin": "Kendimle ilgili her şeyi anlatabileceğim hiç kimse yok.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "385", "metin": "Şimşek çakması da korkularımdan biridir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "386", "metin": "Çok tertipli ve titizim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "387", "metin": "Ailem her davranışıma fazla karışıyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "388", "metin": "Karanlıkta yalnız kalmaktan korkarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "389", "metin": "Tasarlamış olduğum planlar çok defa o kadar güçlükle dolu göründü ki bunlardan vazgeçmek zorunda kaldım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "390", "metin": "Birinin hatasını önleme gayretimin yanlış anlaşılmasına çok üzülürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "391", "metin": "Dansa gitmeyi severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "392", "metin": "Fırtınadan çok korkarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "393", "metin": "Yük çekmeyen atlar dövülmeli ya da kamçılanmalıdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "394", "metin": "Başkalarına sık sık akıl danışırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "395", "metin": "Gelecek, bir insanın ciddi planlar yapamayacağı kadar belirsizdir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "396", "metin": "İşler yolunda gittiği zaman bile çoğu kez her şeye karşı bir aldırmazlık içinde olduğumu hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "397", "metin": "Bazen güçlükler öylesine üst üste gelir ki onlarla baş edemeyecekmişim gibi hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "398", "metin": "Çoğu kez \"Keşke tekrar çocuk olsaydım\" diye düşünürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "399", "metin": "Kolay kolay kızmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "400", "metin": "Eğer bana fırsat verilse dünya için çok yararlı işler yapabilirim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "401", "metin": "Sudan hiç korkmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "402", "metin": "Ne yapacağıma karar vermeden önce uzun uzun düşünürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "403", "metin": "Bir çok şeyin olup bittiği böyle bir devirde yaşamak hoş bir şey.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "404", "metin": "Hatalarını düzelterek kendilerine yardım etmeye çalıştığım insanlar amacımı çoğu kez yanlış anlarlar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "405", "metin": "Yutkunmakta güçlük çekmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "406", "metin": "Uzman dendiği halde benden pek fazla bilgili olmayan insanlarla sıklıkla karşılaşırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "407", "metin": "Genel olarak sakinim ve kolay sinirlenmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "408", "metin": "Bazı konular hakkında hislerimi o kadar gizleyebilirim ki insanlar bilmeden beni incitebilirler.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "409", "metin": "Elimde olmadan çok ufak bir şeyden münakaşa çıkarıp karşımdakini kırıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "410", "metin": "Madrabazı(hilekarı) kendi silahı ile alt etmekten hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "411", "metin": "İyi tanıdığım bir kimsenin başarısını duyduğum zaman adeta kendimi başarısızlığa uğramış hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "412", "metin": "Hastalandığım zaman doktora gitmekten korkmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "413", "metin": "Günahlarım için ne kadar ağır ceza görsem iyidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "414", "metin": "Hayal kırıklıklarını o kadar ciddiye alırım ki bunları zihnimden söküp atamam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "415", "metin": "Fırsat verilse iyi bir önder olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "416", "metin": "Yakınlarımın sağlığından çok endişe ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "417", "metin": "Sırada beklerken biri önüme geçmeye kalkışırsa ona çıkışırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "418", "metin": "Bazen hiçbir işe yaramadığımı düşünürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "419", "metin": "Küçükken okuldan sık sık kaçardım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "420", "metin": "Başımdan dinle ilgili olağan üstü yaşantılar geçti.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "421", "metin": "Ailemde çok sinirli insanlar var.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "422", "metin": "Ailemde bazı kişilerin yapmış olduğu işler beni utandırmıştır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "423", "metin": "Balık tutmayı çok severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "424", "metin": "Hemen hemen her zaman açlık duyarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "425", "metin": "Sık sık rüya görürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "426", "metin": "Kaba ya da can sıkıcı insanlara karşı bazen sert davrandığım olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "427", "metin": "Açık saçık hikayelerden utanıp rahatsız olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "428", "metin": "Gazetelerin baş yazılarını okumaktan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "429", "metin": "Ciddi konular üzerinde verilen konferansları dinlemekten hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "430", "metin": "Karşı cinsten olanları çekici bulurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "431", "metin": "Başa gelebilecek talihsizlikler beni oldukça telaşlandırır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "432", "metin": "Kuvvetli siyasi fikirlerim vardır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "433", "metin": "Bir zamanlar hayali arkadaşlarım vardı.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "434", "metin": "Otomobil yarışçısı olmayı isterdim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "435", "metin": "Genel olarak kadınlarla çalışmayı tercih ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "436", "metin": "İnsanlar genel olarak başkalarının haklarına saygı göstermekten çok kendi haklarına saygı gösterilmesini isterler.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "437", "metin": "Kanuna aykırı davranmadan kanunun bir gediğinden yararlanmakta zarar yoktur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "438", "metin": "Bazı insanlardan o kadar nefret ederim ki ettiklerini bulunca içimden oh derim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "439", "metin": "Beklemek zorunda kalmak beni sinirlendirir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "440", "metin": "Başkalarına anlatmak için hoş fıkraları hatırımda tutmaya çalışırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "441", "metin": "Uzun boylu kadınlardan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "442", "metin": "Üzüntü yüzünden uyuyamadığım zamanlar oldu.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "443", "metin": "Başkalarının gereği gibi yapamadığımı sandığı şeyleri yapmaktan vazgeçtiğim oldu.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "444", "metin": "Başkalarının cahilce inançlarını düzeltmeye çalışmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "445", "metin": "Küçükken heyecan veren şeyler yapmaktan hoşlanırdım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "446", "metin": "Az parayla oynanan kumardan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "447", "metin": "Mastürbasyonda kendi cinsimle ilgili hayal beni tahrik eder.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "448", "metin": "Sokakta, otobüs ve dükkanlarda bana bakan insanlardan rahatsız olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "449", "metin": "İnsanlarla bir arada olmayı sağladığı için toplantı ve davetleri severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "450", "metin": "Kalabalığın verdiği coşkudan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "451", "metin": "Neşeli arkadaşlar arasına karışınca üzüntülerimi unuturum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "452", "metin": "Arkadaş edinemiyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "453", "metin": "Küçükken mahalledeki arkadaş ya da akran gruplarına katılmaktan hoşlanmazdım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "454", "metin": "Orman ya da dağdaki bir kulübede tek başıma yaşamaktan mutlu olabilirim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "455", "metin": "İçinde bulunduğum grubun dedikodularına ve konuşmalarına sıklıkla konu olmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "456", "metin": "İnsan makul bulmadığı kanunlara aykırı hareketlerinden ötürü cezalandırılmamalıdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "457", "metin": "Bence insan hiçbir zaman alkollü bir içkiyi ağzına almamalıdır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "458", "metin": "Çocukken benimle en fazla ilgilenen erkek (baba, üvey baba vb.) bana karşı çok sert davrandı.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "459", "metin": "Çaba göstermekle yenemeyeceğimi bildiğim bazı kötü alışkanlıklarım var.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "460", "metin": "Az içki kullandım ya da hiç kullanmadım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "461", "metin": "Kısa bir zaman için bile olsa başladığım işi bir kenara bırakmak bana güç gelir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "462", "metin": "Küçük abdestimi yapmada ya da tutmada güçlük çekmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "463", "metin": "Sek sek oyunu oynamamaktan hoşlanırdım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "464", "metin": "Hiç hayal görmedim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "465", "metin": "Birkaç kez hayatım boyunca yaptığım işte hevesimi yitirdiğim olmuştur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "466", "metin": "Doktor önerisi dışında hiçbir ilaç ya da uyku hapı kullanmadım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "467", "metin": "Çok defa (otomobil, plaka numarası gibi) hiç önemli olmayan numaraları ezberlerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "468", "metin": "Sıklıkla sinirli ve asık suratlı olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "469", "metin": "Onlardan önce düşündüğüm için başkaları benim fikirlerimi kıskanıyorlar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "470", "metin": "Cinsiyetle ilgili şeylerden nefret ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "471", "metin": "Okulda hal ve gidişten kırık not alırdım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "472", "metin": "Yangın karşısında büyülenmiş gibi olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "473", "metin": "Mümkün olduğu kadar kalabalıktan uzak kalmaya çalışırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "474", "metin": "Başkalarından daha sık küçük abdeste çıkmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "475", "metin": "Sıkıştırıldığım zaman gerçeğin ancak bana zarar vermeyeceği kısmını söylerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "476", "metin": "Tanrı bana özel bir görev vermiştir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "477", "metin": "Arkadaşlarımla birlikte işlediğim bir suçtan eşit şekilde suçlu olduğum zaman onları ele vermektense bütün suçu üzerime almayı tercih ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "478", "metin": "Çok değişik bir aile ortamından gelmiş olmayı isterdim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "479", "metin": "Yabancılarla tanışmaktan kaçınmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "480", "metin": "Karanlıktan çok defa korkarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "481", "metin": "Bir şeyden kurtulmak için hasta numarası yaptığım olmuştur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "482", "metin": "Trende, otobüste vb. rastladığım kimselerle çok defa konuşurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "483", "metin": "Peygamberimiz göğe çıkma gibi mucizeler göstermiştir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "484", "metin": "Homoseksüelliği çok iğrenç buluyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "485", "metin": "Bir erkek bir kadınla beraber olunca genel olarak onun cinsiyetiyle ilgili şeyler düşünür.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "486", "metin": "İdrarımda hiçbir zaman kan görmedim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "487", "metin": "Uğraştığım iş yolunda gitmeyince hemen vazgeçerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "488", "metin": "Sık sık dua ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "489", "metin": "Yaşamı yalnızca üzüntülü, sıkıntılı tarafları ile benimseyen insanlara sempati duyarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "490", "metin": "Haftada birkaç kere Kur'an okurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "491", "metin": "Sadece bir tek dinin doğruluğuna inananlara tahammül edemem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "492", "metin": "Zelzele düşüncesi beni çok korkutur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "493", "metin": "Tam dikkat isteyen işleri, beni dikkatsizliğe sürükleyen işlere tercih ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "494", "metin": "Kapalı ve küçük yerlerde bulunmaktan çok rahatsız olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "495", "metin": "Kusurlarını düzeltmeye çalıştığım insanlarla genel olarak gayet açık konuşurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "496", "metin": "Eşyayı hiçbir zaman çift görmem (Yani tek olan şeyleri çift görmem.)", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "497", "metin": "Macera hikayelerinden hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "498", "metin": "Açık sözlü olmak her zaman iyidir iyidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "499", "metin": "Gerçekten önemsiz olan bir şey üzerinde bazen sebepsiz olarak haddinden fazla üzüldüğüm olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "500", "metin": "Bana parlak gelen bir fikre hemen kapılır giderim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "501", "metin": "Başkalarından yardım beklemektense genel olarak bir işi kendi başıma yapmayı tercih ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "502", "metin": "Herhangi bir olay hakkındaki görüşümü başkalarına açıkça belirtmekten hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "503", "metin": "Başkalarının hareketlerini çok beğenip beğenmediğimi pek belli etmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "504", "metin": "Değersiz gördüğüm ya da acıdığım kimseye bu duygularımı belli etmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "505", "metin": "Zaman zaman kendimi öyle güçlü ve enerjik hissederim ki böyle zamanlarda günlerce uykuya ihtiyat duymadığım olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "506", "metin": "Sinirleri çok gergin bir insanım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "507", "metin": "İşler iyi gidince aslan payını kendilerine alan fakat hata yapılınca bunu başkalarının üzerine atan insanlarla karşılaştım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "508", "metin": "Koku alma duyum herkes kadar iyidir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "509", "metin": "Bazen çekingenliğim yüzünden hakkımı arayamam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "510", "metin": "Pislik ve kir beni ürkütüp iğrendirir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "511", "metin": "Herkesten gizli tuttuğum bir hayal dünyam var.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "512", "metin": "Yıkanmaktan hoşlanmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "513", "metin": "Kış mevsimini severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "514", "metin": "Erkek gibi davranan kadınlardan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "515", "metin": "Evimizde daima gerekli ihtiyaç maddeleri bulunurdu (yeteri kadar yiyecek, giyecek vs. gibi).", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "516", "metin": "Ailemde çabuk kızan kimseler var.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "517", "metin": "Hiçbir şeyi iyi yapamam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "518", "metin": "Bazı durumlarda olduğumdan daha fazla üzüntülü görünmeye çalıştığım olmuştur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "519", "metin": "Cinsel organlarımda bir bozukluk var.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "520", "metin": "Genel olarak görüşlerimi kuvvetle savunurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "521", "metin": "Bir grup içinde konuşma yapmam ve çok iyi bildiğim bir konuda fikrimi söylemem istenince kaygılanmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "522", "metin": "Örümcekten korkmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "523", "metin": "Yüzüm hemen hemen hiç kızarmaz.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "524", "metin": "Kapı tokmaklarından hastalık veya mikrop alacağımdan korkmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "525", "metin": "Bazı hayvanlardan ürkerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "526", "metin": "Gelecek bana ümitsiz görünüyor.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "527", "metin": "Ailem ve yakın akrabalarım birbirleri ile oldukça iyi geçinirler.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "528", "metin": "Yüzüm başkalarından daha sık kızarmaz.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "529", "metin": "Pahalı elbiseler giymeyi isterim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "530", "metin": "Sebepsiz yere sık sık içim sıkılıyor ve ağlamak istiyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "531", "metin": "Bir konu üzerinde karar verdiğimi zannetsem bile başka biri fikrimi kolayca değiştirebilir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "532", "metin": "Acıya başkaları kadar ben de dayanabilirim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "533", "metin": "Sık sık geğirmekten şikayetim yoktur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "534", "metin": "Çoğunlukla başladığım işten en son vazgeçen ben olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "535", "metin": "Hemen hemen her zaman ağzımda kuruluk olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "536", "metin": "Beni acele ettirenlere kızarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "537", "metin": "Afrika'da arslan avına çıkmak isterdim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "538", "metin": "Terzilikten hoşlanabileceğimi sanmıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "539", "metin": "Fareden korkmam.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "540", "metin": "Yüzüme hiç felç inmedi.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "541", "metin": "Cildime ufak bir şeyin dokunmasından çok huylanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "542", "metin": "Şimdiye kadar rengi kapkara büyük abdest yapmadım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "543", "metin": "Haftada birkaç kez korkunç bir şey olacakmış duygusuna kapılırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "544", "metin": "Çoğu zaman yorgunluk hissederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "545", "metin": "Bazen aynı rüyayı tekrar tekrar görürüm.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "546", "metin": "Tarih okumaktan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "547", "metin": "Toplantı ve kalabalık eğlencelerden hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "548", "metin": "Elimdeyse açık saçık numaraların yapılacağı eğlence yerlerine gitmem.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "549", "metin": "Karşıma çıkacak güçlüklerden korkar ve kaçarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "550", "metin": "Kapı mandallarını onarmaktan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "551", "metin": "Bazen başkalarının kafamın içindekileri okuduğundan eminim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "552", "metin": "Bilimsel yayınları okumaktan hoşlanırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "553", "metin": "Açık yerlerde veya geniş meydanlarda tek başıma kalmaktan korkarım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "554", "metin": "Sıkıntım oldukça alkol alırım.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "555", "metin": "Bazen çıldıracakmış gibi olurum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "556", "metin": "Kılık kıyafetime çok dikkat ederim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "557", "metin": "Hayatı fazla ciddiye almıyorum.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "558", "metin": "Birçok kimseler kötü cinsel faaliyetlerinden dolayı suçludurlar.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "559", "metin": "Gece yarısı çoğunlukla korkuya kapıldığım olur.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "560", "metin": "Bir şeyi nereye koyduğumu unutmaktan çok şikayetçiyimdir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "561", "metin": "Ailem benim için büyük bir dayanaktır.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "562", "metin": "Çocukken en fazla bağlandığım ve hayran kaldığım kimse bir kadındı.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "563", "metin": "Macera hikayelerini aşk hikayelerinden daha çok severim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "564", "metin": "Yapmak istediğim fakat başkalarının beğenmediği bir işten kolayca vazgeçerim.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "565", "metin": "Yüksek bir yerde iken içimden atlama isteği gelir.", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] },
    { "id": "566", "metin": "Son soru (örnek)", "secenekler": [{"metin": "DOĞRU", "puan": 1}, {"metin": "YANLIŞ", "puan": 0}] }
] as const;

// Not: Puanlama anahtarları, K-düzeltmesi ve T-skoru norm tabloları
// bu dosyadan KALDIRILDI. Tekil ve resmi kaynak dosyalar kullanılacaktır:
// - Puanlama anahtarları: src/lib/mmpi/data/scoringKeys.ts (scoringKeys, kCorrectionFactors)
// - Türk normları: src/lib/mmpi/data/turkishNorms.ts (turkishNorms, kCorrectionRatios)
// Bu dosyada SADECE soruların ham verisi tutulur.
